import { AlertTriangle, HeartPulse, ShieldAlert, Thermometer } from "lucide-react";
import PageShell, { IconFrame, panel } from "../components/PageShell";

const alerts = [
  { code: "D11-709", name: "Bull CAT D11", issue: "Hydraulic pressure below operating range", temp: "84°C", score: 41, level: "CRITICAL" },
  { code: "KOM 303", name: "Komatsu 730E", issue: "Engine temperature trend rising", temp: "92°C", score: 68, level: "WARNING" },
  { code: "CAT 211", name: "Caterpillar 777", issue: "Payload variance above shift baseline", temp: "76°C", score: 72, level: "WARNING" },
];

export default function Anomalies() {
  return <PageShell><div className="h-full flex flex-col gap-5">
    <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-rose-400 text-xs font-mono uppercase tracking-[0.22em]">OCP Zone 4 / ALERTS</p><h1 className="text-white font-bold tracking-tight text-3xl">Anomaly Detection</h1><p className="text-zinc-500 text-sm mt-1">Machine health signals requiring attention from the control room.</p></div><span className="px-2.5 py-1 rounded-full text-[10px] font-mono font-bold bg-rose-500/10 border border-rose-500/20 text-rose-400">3 OPEN ALERTS</span></div>
    <div className="grid grid-cols-1 md:grid-cols-3 gap-5"><div className={panel}><div className="flex items-center gap-3"><IconFrame className="text-rose-400"><ShieldAlert className="w-5 h-5" /></IconFrame><div><p className="text-zinc-500 text-xs">CRITICAL MACHINES</p><p className="font-mono text-3xl font-bold text-white">01</p></div></div></div><div className={panel}><div className="flex items-center gap-3"><IconFrame className="text-amber-400"><AlertTriangle className="w-5 h-5" /></IconFrame><div><p className="text-zinc-500 text-xs">AT RISK</p><p className="font-mono text-3xl font-bold text-white">02</p></div></div></div><div className={panel}><div className="flex items-center gap-3"><IconFrame><HeartPulse className="w-5 h-5" /></IconFrame><div><p className="text-zinc-500 text-xs">FLEET HEALTH AVG</p><p className="font-mono text-3xl font-bold text-white">76<span className="text-sm text-zinc-500">/100</span></p></div></div></div></div>
    <section className={`${panel} flex-1 min-h-0 overflow-auto`}><div className="flex items-center gap-3 mb-5"><IconFrame className="text-rose-400"><AlertTriangle className="w-5 h-5" /></IconFrame><div><h2 className="text-white font-bold tracking-tight text-lg">Open alerts</h2><p className="text-zinc-500 text-xs">Prioritized by health impact and telemetry confidence</p></div></div><div className="grid grid-cols-1 xl:grid-cols-3 gap-4">{alerts.map((alert) => <article key={alert.code} className="rounded-2xl border border-white/10 bg-black/20 p-4 hover:bg-white/10 hover:border-white/20 transition-all"><div className="flex items-start justify-between gap-3"><div className="flex items-center gap-3"><IconFrame className={alert.level === "CRITICAL" ? "text-rose-400" : "text-amber-400"}><Thermometer className="w-4 h-4" /></IconFrame><div><h3 className="font-mono font-bold text-white">{alert.code}</h3><p className="text-xs text-zinc-500">{alert.name}</p></div></div><span className={`px-2.5 py-1 rounded-full text-[10px] font-mono font-bold border ${alert.level === "CRITICAL" ? "bg-rose-500/10 border-rose-500/20 text-rose-400" : "bg-amber-500/10 border-amber-500/20 text-amber-400"}`}>{alert.level}</span></div><p className="mt-5 text-sm text-zinc-300">{alert.issue}</p><div className="mt-5 flex items-end justify-between"><div><p className="text-[10px] text-zinc-500">TEMPERATURE</p><p className="font-mono text-lg text-white">{alert.temp}</p></div><div className="text-right"><p className="text-[10px] text-zinc-500">HEALTH SCORE</p><p className={`font-mono text-lg ${alert.score < 50 ? "text-rose-400" : "text-amber-400"}`}>{alert.score}/100</p></div></div><div className="mt-3 h-1.5 rounded-full bg-white/10"><div className={`h-full rounded-full ${alert.score < 50 ? "bg-rose-500" : "bg-amber-400"}`} style={{ width: `${alert.score}%` }} /></div></article>)}</div></section>
  </div></PageShell>;
}
